export const themes = [
  {
    id: "violet",
    name: "Violet",
    primary: "#6551d3",
    secondary: "#24a88c",
    tertiary: "#e89655",
  },
  {
    id: "ocean",
    name: "Ocean",
    primary: "#1677b8",
    secondary: "#24a8a0",
    tertiary: "#a2a932",
  },
  {
    id: "forest",
    name: "Forest",
    primary: "#23815b",
    secondary: "#a2a932",
    tertiary: "#24a8a0",
  },
  {
    id: "rose",
    name: "Rose",
    primary: "#c04e78",
    secondary: "#e89655",
    tertiary: "#8c6bc9",
  },
  {
    id: "amber",
    name: "Amber",
    primary: "#b66a14",
    secondary: "#267f83",
    tertiary: "#c04e78",
  },
  {
    id: "slate",
    name: "Slate",
    primary: "#52647d",
    secondary: "#8c6bc9",
    tertiary: "#24a88c",
  },
  {
    id: "cloud",
    name: "Cloud",
    primary: "#52647d",
    secondary: "#24a8a0",
    tertiary: "#c04e78",
  },
  {
    id: "dark-violet",
    name: "Night Violet",
    primary: "#a695ff",
    secondary: "#4fd1b6",
    tertiary: "#e896ff",
  },
  {
    id: "dark-ocean",
    name: "Night Ocean",
    primary: "#66c8ff",
    secondary: "#5cd6c3",
    tertiary: "#a695ff",
  },
  {
    id: "dark-forest",
    name: "Night Forest",
    primary: "#6bd6a0",
    secondary: "#d0db72",
    tertiary: "#66c8ff",
  },
  {
    id: "dark-rose",
    name: "Night Rose",
    primary: "#ff91b3",
    secondary: "#ffc279",
    tertiary: "#a695ff",
  },
  {
    id: "dark-graphite",
    name: "Graphite",
    primary: "#c4cbd5",
    secondary: "#7e8998",
    tertiary: "#4c5665",
  },
  {
    id: "dark-slate",
    name: "Ash",
    primary: "#d3d7dc",
    secondary: "#89939f",
    tertiary: "#596575",
  },
  {
    id: "dark-midnight",
    name: "Midnight Grey",
    primary: "#b7bec8",
    secondary: "#697584",
    tertiary: "#394453",
  },
] as const;

export type ThemeId = (typeof themes)[number]["id"];
